### PR TITLE
Updated file upload process to be multi-threaded

### LINKED ISSUE #1: Add threading to file upload
Followup to 1fc9b58 since adding threading to multi-file upload is not simple due to how it returns json results.

### PR DESCRIPTION
**Pull request by ajbozarth**
Closes #1

### CODE REVIEW

**Comment by ajbozarth** [comment]
@djalova could you take a test run at this to double check it works? maybe also test it with docker since I didn't.

@lresende this is a followup to your threading pr, mind taking a look?

My plan is to cut an official v2.0 once this is merged and update our long-running demo machines.

**Comment by djalova** [comment]
Tested it out and it works, but it doesn't provide a noticeable speedup.

**Comment by ajbozarth** [comment]
The speedup is very marginal when running on the same machine, but it becomes much more noticeable when the model api is on a different machine than the web app

**Comment by djalova** [comment]
Alright LGTM then

**Pull request merged**
