### PR TITLE
Added Depoly to IBM Cloud Support

### LINKED ISSUE #7: Add Deploy to IBM Cloud support
Internal Requirements Doc:
https://pages.github.ibm.com/IBMCode/IBMCodeContent/patterns/dev/#6-add-deploy-to-ibm-cloud-support

### PR DESCRIPTION
**Pull request by ajbozarth**
Includes a Deploy to IBM Cloud button and a manifest.yml file that uses a static ML end point on IBM Cloud

Closes #7

### CODE REVIEW

**Comment by ajbozarth** [comment]
@rhagarty Two question for you on this pr:
1. I used a static ip for the ml-endpoint when deploying to IBM Cloud. That end point is a permanent one that CODAIT set up on IBM Cloud with the plan to make it publicly known as a permanent access point in the future. Is having this static ok in a Code Pattern or do we need to find a way for the user to deploy the model to IBM cloud and chain them together?
2. I can't seem to find any documentation on how to add the badge for tracking the number of times the web app has been deployed. It almost seemly like the feature was deprecated from what I could find.

**Comment by ajbozarth** [comment]
Note this is WIP since I still need to add actually instructions after the deploy button, though it will just be a screen shot telling them to click the web button once it's finished deploying.

**Comment by rhagarty** [comment]
1 - not sure about that. If the plans are to make it public, it seems fine. Would be better if this was a host name. 
2 - the tracking badges has issues, so we removed it from the code patterns.

**Comment by ajbozarth** [comment]
Added deploy steps if you could take a look @djalova @rhagarty

**Comment by djalova** [comment]
LGTM

**Pull request merged**
