### PR TITLE
Update Kube yaml file to new MAX standard

### PR DESCRIPTION
**Pull request by ajbozarth**
As part of https://github.ibm.com/CODAIT/Usability-Enhancement/issues/2 we're updating the kube yaml files to a standard matching https://kubernetes.io/docs/concepts/configuration/overview/

This update depends on https://github.com/IBM/MAX-Image-Caption-Generator/pull/7 which updates the model yaml file to the same standard.

### CODE REVIEW

**Comment by ajbozarth** [comment]
If everyone can go through the steps and make sure this all works. Note that the urls in the readme won't work since this and IBM/MAX-Image-Caption-Generator#7aren't merged so you'll need to use the files in each PR directly (either by downloading them or referencing their blob urls)

**Comment by ajbozarth** [comment]
@lresende if you could also test this (can't seem to add you as a reviewer)

**Comment by ajbozarth** [comment]
Accidentally made a commit meant for my other pr on this one, rolled it back

**Comment by ajbozarth** [comment]
Further note: Unlike my note on the related model PR, these updates are primarily superficial. The yaml file is just rearranged to match the new model yaml standard and the documentation is updated to match and note the changes in the model PR.

**Comment by ajbozarth** [comment]
Also @nheidloff could you take a look at and try out these kubernetes updates since you proposed the original kube deploy PR?

**Comment by ajbozarth** [comment]
Based on @ptitzler feedback and scrum discussion I've changed LoadBalancer back to NodePort to allow for use on IBM Cloud free tier

**Comment by ajbozarth** [comment]
I made a few updates based on changes made to IBM/MAX-Image-Caption-Generator#7
After a discussion at scrum we decided to revert back to using a `NodePort` rather than a `LoadBalancer` for the model yaml. This means changing the port visibility README section here back to clarify that the model is available at the `NodePort` not `5000`. I also added a note recommending users to use the Deploy to IBM Cloud instructions for the web app and not the Kubernetes instructions with IBM Cloud Kubernetes services. This is because the current web app yaml file still uses `LoadBalancer` which is not supported by IBM Cloud Kubernetes Service free tier.

So if everyone could review the text changes and give feedback on wether the note is good enough or if you think we should switch to using `NodePort` for the web app as well.

**Comment by ajbozarth** [comment]
1. For the web app we specifically don't want users to deploy to IBM Cloud Kube Service but instead follow the guide for Cloud Foundry. Thus we're leaving it as a `LoadBalancer` since it is the preferred web app deployment type. (Using `LoadBalancer` here was what originally got me to change the models to it).
2. I'm not sure what you mean here, the README specifies that you need to enter the model API endpoint created in the first section.
3. If we want to update this particular repo to use the `$` convention that would be another pr. Not using `$` was decided by the repo committers during the code pattern process so not using it here follows that decision.

**Comment by ptitzler** [comment]
#1 the readme states: 
> You can also deploy the model and web app on Kubernetes using the latest docker images on Docker Hub.

If we don't want users to follow the approach we shouldn't document the approach and include a kubernetes configuration file

#2: Yes, but when one configures the deployment pipeline one also has to provide an IBM CLOUD API  key, not just the model endpoint. 

#3 okay

**Comment by ptitzler** [comment]
image

**Comment by ajbozarth** [comment]
For 1, that's why the Kube section follows the IBM Cloud section, to show that the IBM Cloud section takes precedence. I also added the note in the Kube section clarifying that it was not for IBM Cloud and to use the prior section for IBM Cloud. The Kube section is for generic kube deployment not IBM Cloud, it was specifically requested in a non-CODAIT PR (which is what triggered my work in adding MAX Kube support).

For 2, I'm not sure why you're seeing that, no one (which is quite a few people) have had that field shown before. It's also interesting that your region/org/space is not filled by default either. It seems that it may be a separate issue outside the scope of this PR.

**Comment by ajbozarth** [comment]
Ok so I just tried it myself and that is new. They must have changed the Deploy to IBM Cloud functionality (again) since this code pattern was published. You can open an issue to address it.

**Pull request merged**
