### PR TITLE
Added Acknowledgements Doc

### PR DESCRIPTION
**Pull request by ajbozarth**
Since Fred was integral to the creation of this code pattern but has no commits I thought we should add this optional doc to give him credit.

### CODE REVIEW

**Comment by djalova** [comment]
LGTM

**Comment by ajbozarth** [comment]
@djalova Since the commits are squashed I can't check, but did you do most of the work on this model? I know Nick started the work and you finished it.

**Comment by djalova** [comment]
@ajbozarth Yeah, Nick created a base template for all the MAX models and I worked on this specific model.

**Comment by ajbozarth** [comment]
thought so, @stevemart given Daniel is a co-author on this project I think this is fine as is. merging

**Comment by stevemart** [comment]
👍

**Pull request merged**
